export const projects = [
    {
        id: 1,
        name: 'Intro Section',
        code: 'https://github.com/Umlen/intro-section',
        demo: 'https://intro-section-gold.vercel.app/',
        screenshot: '/images/projects/intro-section.png',
    },
    {
        id: 2,
        name: 'Todo App',
        code: 'https://github.com/Umlen/todo-app',
        demo: 'https://todo-app-tau-livid.vercel.app/',
        screenshot: '/images/projects/todo-app.png',
    },
    {
        id: 3,
        name: 'Tip Calculator App',
        code: 'https://github.com/Umlen/tip-calculator-app',
        demo: 'https://tip-calculator-app-orpin.vercel.app/',
        screenshot: '/images/projects/tip-calculator-app.png',
    },
    {
        id: 4,
        name: 'Room Homepage',
        code: 'https://github.com/Umlen/room-homepage',
        demo: 'https://room-homepage-gamma.vercel.app/',
        screenshot: '/images/projects/room-homepage.png',
    },
    {
        id: 5,
        name: 'React 25 + 5 Clock',
        code: 'https://codepen.io/Umlen/pen/abqJKXz',
        demo: 'https://codepen.io/Umlen/full/abqJKXz',
        screenshot: '/images/projects/25-clock.png',
    },
    {
        id: 6,
        name: 'React Markdown Previewer',
        code: 'https://codepen.io/Umlen/pen/BaYNGOO',
        demo: 'https://codepen.io/Umlen/full/BaYNGOO',
        screenshot: '/images/projects/react-markdown-previewer.png',
    },
    {
        id: 7,
        name: 'Password Generator',
        code: 'https://github.com/Umlen/solo-project-password-generator',
        demo: 'https://euphonious-creponne-ac6f32.netlify.app/',
        screenshot: '/images/projects/password-generator.png',
    },
    {
        id: 8,
        name: 'Unit Converter',
        code: 'https://github.com/Umlen/solo-project-unit-converter',
        demo: 'https://rainbow-squirrel-0aa10b.netlify.app/',
        screenshot: '/images/projects/unit-converter.png',
    },
]